steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/money-tracker', .]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/money-tracker']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'money-tracker',
        '--image',
        'gcr.io/$PROJECT_ID/money-tracker',
        '--platform',
        'managed',
        '--region',
        'asia-southeast1-a',
        '--allow-unauthenticated',
      ]
