create type category_type_enum as enum ('expense', 'income');

create table
    "category" (
        "id" int generated by default as identity primary key,
        "name" varchar(255) not null unique,
        "slug" varchar(255) not null unique,
        "type" category_type_enum not null
    );

create index "category_type_index" on "category" ("type");